# Generated by Django 4.1.7 on 2023-02-18 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.CharField(choices=[('VENDEDOR', 'Vendedor'), ('CLIENTE', 'Cliente')], default='Cliente', max_length=10),
        ),
    ]
