# Generated by Django 4.1.7 on 2023-02-18 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_user_groups_user_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.CharField(choices=[('CLIENTE', 'Cliente'), ('VENDEDOR', 'Vendedor')], default='Cliente', max_length=10, verbose_name='Grupo'),
        ),
    ]
