# Generated by Django 4.1.7 on 2023-02-18 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_user_groups_user_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='d2482c2b-cc75-4be1-90a3-a55b89e027ee', max_length=35, unique=True),
        ),
    ]
