# Generated by Django 4.1.7 on 2023-02-18 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_user_groups_model_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funfapls', models.CharField(max_length=500)),
            ],
        ),
    ]
