# Generated by Django 4.1.7 on 2023-02-22 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Endereços'},
        ),
        migrations.AddField(
            model_name='address',
            name='selected',
            field=models.BooleanField(default=False, verbose_name='Selecionado'),
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adresses', to='accounts.address', verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Estado'),
        ),
    ]
