# Generated by Django 4.1.7 on 2023-02-22 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_category_options_alter_product_options'),
        ('accounts', '0020_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='adresses', to='products.product', verbose_name='Product'),
            preserve_default=False,
        ),
    ]
