# Generated by Django 4.1.7 on 2023-02-22 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_address_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='product',
        ),
    ]
