# Generated by Django 4.1.7 on 2023-02-22 04:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_remove_address_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='user',
        ),
        migrations.AddField(
            model_name='address',
            name='user',
            field=models.ManyToManyField(related_name='adresses', to=settings.AUTH_USER_MODEL, verbose_name='Endereços'),
        ),
    ]
