# Generated by Django 4.1.7 on 2023-02-22 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_remove_address_user_address_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.ManyToManyField(related_name='users', to='accounts.address', verbose_name='Endereços'),
        ),
    ]
