# Generated by Django 4.1.7 on 2023-02-22 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-created_at',), 'verbose_name_plural': 'Pedidos'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ('-order',), 'verbose_name_plural': 'Items do pedido'},
        ),
    ]
